#!/bin/sh

# ------------
# Installation
# ------------
#
# 1. Copy this script to the 'hooks' directory of your respository. For gitolite
#    hosted respositories this will be something like:
#
#    '/srv/git/repositories/[your-repository-name]/hooks/post-receive'
#
# 2. Modfy 'launch_dir' below to point to the installation directory of the
#    launch source tree.

# Path to the repository to be deployed.
repo_dir=`pwd`

# Path to the launch-server application.
launch_dir="/home/ben/rohben/launch-server"

# The Jakefile does all the work.
jake --jakefile ./hooks/Jakefile.js repo=${repo_dir} launch_app=${launch_dir} post-receive
