#!/bin/sh

# ------------
# Installation
# ------------
#
# 1. Copy this script to the 'hooks' directory of your respository. For gitolite
#    hosted respositories this will be something like:
#
#    '/srv/git/repositories/[your-repository-name]/hooks/post-receive'
#
# 2. Modfy 'launch_dir' below to point to the installation directory of the
#    launch source tree.

# Path to the repository to be deployed.
repo_dir=`pwd`

# Path to the launch-server application.
launch_dir="${repo_dir}/hooks/launch"

# The node script does all the work.
node ./hooks/post-receive.js ${launch_dir} ${repo_dir}
